dist: trusty
language: node_js
node_js:
- 9.11.1
jobs:
  include:
  - stage: test
    addons:
      chrome: stable
    services:
    - mongodb
    cache:
      directories:
      - node_modules
    before-install:
    - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost
      &
    install:
    - npm install
    before-script:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - sleep 3
    script:
    - npm run client-test
    - npm run api-test
    - npm run build:dev
  - stage: deploy
    sudo: required
    services:
    - docker
    before_install:
    - openssl aes-256-cbc -K $encrypted_74b81b802040_key -iv $encrypted_74b81b802040_iv
      -in secret_configs.tar.enc -out secret_configs.tar -d
    - tar xvf secret_configs.tar
    install:
    - npm install esdoc esdoc-node
    script:
    - npm run docs
    - bash deploy.sh

    deploy:
      provider: pages
      skip_cleanup: true
      github_token: "$GITHUB_TOKEN"
      local_dir: docs/
      on:
        branch: master
notifications:
  email: false
