language: node_js
node_js:
  - 9.11.1

env:
  - DOCKER_COMPOSE_VERSION=1.8.0

services:
  - docker

cache:
  directories:
    - "node_modules"

install:
  - npm install

before_script:
  - docker -v
  - docker-compose -v
  - docker-machine -v
  - docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}

script:
  - npm run client-test
  - npm run api-test

after-script:

  - docker build -t acmtexastech/ttuweb .
  - docker push acmtexastech/ttuweb

notifications:
  email: false
