dist: trusty
language: node_js
node_js:
  - 9.11.1

addons:
  chrome: stable

services:
  - mongodb

cache:
  directories:
    - "node_modules"

before-install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

install:
  - npm install

before-script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
  - npm run client-test
  - npm run api-test

after-success:
  - npm run docs

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: docs/
  on:
    branch: master

notifications:
  email: false
