dist: trusty
language: node_js
node_js:
- 9.11.1
addons:
  chrome: stable
services:
- mongodb
cache:
  directories:
  - node_modules
before-install:
- google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost
  &
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- openssl aes-256-cbc -K $encrypted_74b81b802040_key -iv $encrypted_74b81b802040_iv
  -in environment.prod.ts.enc -out src/environments/environment.prod.ts -d
- openssl aes-256-cbc -K $encrypted_74b81b802040_key -iv $encrypted_74b81b802040_iv
  -in .env.enc -out .env -d
- sleep 3

# install:
# - npm install

script:
- ls -a
- printenv
# - npm run client-test
# - npm run api-test
# - npm run build:dev
# after_success:
# - npm run docs
# - rm -rf .env

# deploy:
#   provider: pages
#   skip_cleanup: true
#   github_token: "$GITHUB_TOKEN"
#   local_dir: docs/
#   on:
#     branch: master
# notifications:
#   email: false
