language: node_js
node_js:
  - 9.11.1

cache:
  directories:
    - "node_modules"

install:
  - npm install

script:
  # - npm run client-test
  # - npm run api-test
  # - npm run docs

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: docs/
  on:
    branch: master

notifications:
  email: false
