dist: trusty
language: node_js
node_js:
  - 9.11.1

addons:
  chrome: stable

services:
  - mongodb
  - docker

cache:
  directories:
  - "node_modules"

before-install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

install:
  - npm install

script:
  - npm run client-test
  - npm run api-test

after_success:
  - npm run docs
  - docker build -t miggylol/travis-ci:${TRAVIS_BRANCH} .

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: "$GITHUB_TOKEN"
    local_dir: docs/
    on:
      branch: master

  - provider: script
    script: bash deploy.sh

notifications:
  email: false
