window.esdocSearchIndex = [
  [
    "ttuacm-backend/ttuacm-backend/src/auth/auth.model.js~authmodel",
    "class/ttuacm-backend/src/auth/auth.model.js~AuthModel.html",
    "<span>AuthModel</span> <span class=\"search-result-import-path\">ttuacm-backend/ttuacm-backend/src/auth/auth.model.js</span>",
    "class"
  ],
  [
    "ttuacm-backend/ttuacm-backend/src/email/email.controller.js~emailcontroller",
    "class/ttuacm-backend/src/email/email.controller.js~EmailController.html",
    "<span>EmailController</span> <span class=\"search-result-import-path\">ttuacm-backend/ttuacm-backend/src/email/email.controller.js</span>",
    "class"
  ],
  [
    "ttuacm-backend/ttuacm-backend/src/events/events.controller.js~eventscontroller",
    "class/ttuacm-backend/src/events/events.controller.js~EventsController.html",
    "<span>EventsController</span> <span class=\"search-result-import-path\">ttuacm-backend/ttuacm-backend/src/events/events.controller.js</span>",
    "class"
  ],
  [
    "ttuacm-backend/ttuacm-backend/src/utils/request.js~request",
    "class/ttuacm-backend/src/utils/request.js~Request.html",
    "<span>Request</span> <span class=\"search-result-import-path\">ttuacm-backend/ttuacm-backend/src/utils/request.js</span>",
    "class"
  ],
  [
    "ttuacm-backend/ttuacm-backend/src/utils/db-connect.js~connectdb",
    "function/index.html#static-function-connectDB",
    "<span>connectDB</span> <span class=\"search-result-import-path\">ttuacm-backend/ttuacm-backend/src/utils/db-connect.js</span>",
    "function"
  ],
  [
    "ttuacm-backend/ttuacm-backend/src/utils/request.js~errorhandler",
    "function/index.html#static-function-errorHandler",
    "<span>errorHandler</span> <span class=\"search-result-import-path\">ttuacm-backend/ttuacm-backend/src/utils/request.js</span>",
    "function"
  ],
  [
    "ttuacm-backend/ttuacm-backend/src/contacts/contacts.model.js~formatgroupname",
    "function/index.html#static-function-formatGroupName",
    "<span>formatGroupName</span> <span class=\"search-result-import-path\">ttuacm-backend/ttuacm-backend/src/contacts/contacts.model.js</span>",
    "function"
  ],
  [
    "ttuacm-backend/ttuacm-backend/src/utils/generate-hex.js~generatehextoken",
    "function/index.html#static-function-generateHexToken",
    "<span>generateHexToken</span> <span class=\"search-result-import-path\">ttuacm-backend/ttuacm-backend/src/utils/generate-hex.js</span>",
    "function"
  ],
  [
    "ttuacm-backend/ttuacm-backend/src/utils/generate-jwt.js~generatejwttoken",
    "function/index.html#static-function-generateJWTToken",
    "<span>generateJWTToken</span> <span class=\"search-result-import-path\">ttuacm-backend/ttuacm-backend/src/utils/generate-jwt.js</span>",
    "function"
  ],
  [
    "ttuacm-backend/ttuacm-backend/src/utils/protected-route.js~membersonlyroute",
    "variable/index.html#static-variable-membersOnlyRoute",
    "<span>membersOnlyRoute</span> <span class=\"search-result-import-path\">ttuacm-backend/ttuacm-backend/src/utils/protected-route.js</span>",
    "variable"
  ],
  [
    "ttuacm-backend/ttuacm-backend/src/auth/config/passport.js~passport",
    "function/index.html#static-function-passport",
    "<span>passport</span> <span class=\"search-result-import-path\">ttuacm-backend/ttuacm-backend/src/auth/config/passport.js</span>",
    "function"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "https://developer.mozilla.org/en/docs/Web/API/AudioContext",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "https://developer.mozilla.org/en-US/docs/Web/API/DocumentFragment",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "https://developer.mozilla.org/en-US/docs/Web/API/Element",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "https://developer.mozilla.org/en-US/docs/Web/API/Event",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "https://developer.mozilla.org/en-US/docs/Web/API/Node",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "https://developer.mozilla.org/en-US/docs/Web/API/NodeList",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "https://developer.mozilla.org/en/docs/Web/API/XMLHttpRequest",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "ttuacm-backend/src/auth/auth.app.js",
    "file/ttuacm-backend/src/auth/auth.app.js.html",
    "ttuacm-backend/src/auth/auth.app.js",
    "file"
  ],
  [
    "ttuacm-backend/src/auth/auth.controller.js",
    "file/ttuacm-backend/src/auth/auth.controller.js.html",
    "ttuacm-backend/src/auth/auth.controller.js",
    "file"
  ],
  [
    "ttuacm-backend/src/auth/auth.controller.spec.js",
    "file/ttuacm-backend/src/auth/auth.controller.spec.js.html",
    "ttuacm-backend/src/auth/auth.controller.spec.js",
    "file"
  ],
  [
    "ttuacm-backend/src/auth/auth.errors.js",
    "file/ttuacm-backend/src/auth/auth.errors.js.html",
    "ttuacm-backend/src/auth/auth.errors.js",
    "file"
  ],
  [
    "ttuacm-backend/src/auth/auth.model.js",
    "file/ttuacm-backend/src/auth/auth.model.js.html",
    "ttuacm-backend/src/auth/auth.model.js",
    "file"
  ],
  [
    "ttuacm-backend/src/auth/auth.model.js~authmodel#constructor",
    "class/ttuacm-backend/src/auth/auth.model.js~AuthModel.html#instance-constructor-constructor",
    "ttuacm-backend/src/auth/auth.model.js~AuthModel#constructor",
    "method"
  ],
  [
    "ttuacm-backend/src/auth/auth.model.js~authmodel#createnewuser",
    "class/ttuacm-backend/src/auth/auth.model.js~AuthModel.html#instance-method-createNewUser",
    "ttuacm-backend/src/auth/auth.model.js~AuthModel#createNewUser",
    "method"
  ],
  [
    "ttuacm-backend/src/auth/auth.model.js~authmodel#findallusers",
    "class/ttuacm-backend/src/auth/auth.model.js~AuthModel.html#instance-method-findAllUsers",
    "ttuacm-backend/src/auth/auth.model.js~AuthModel#findAllUsers",
    "method"
  ],
  [
    "ttuacm-backend/src/auth/auth.model.js~authmodel#getuserbyattribute",
    "class/ttuacm-backend/src/auth/auth.model.js~AuthModel.html#instance-method-getUserByAttribute",
    "ttuacm-backend/src/auth/auth.model.js~AuthModel#getUserByAttribute",
    "method"
  ],
  [
    "ttuacm-backend/src/auth/auth.model.js~authmodel#getuserbyid",
    "class/ttuacm-backend/src/auth/auth.model.js~AuthModel.html#instance-method-getUserById",
    "ttuacm-backend/src/auth/auth.model.js~AuthModel#getUserById",
    "method"
  ],
  [
    "ttuacm-backend/src/auth/auth.model.js~authmodel#mergeaccounts",
    "class/ttuacm-backend/src/auth/auth.model.js~AuthModel.html#instance-method-mergeAccounts",
    "ttuacm-backend/src/auth/auth.model.js~AuthModel#mergeAccounts",
    "method"
  ],
  [
    "ttuacm-backend/src/auth/auth.model.js~authmodel#updateuserbyattribute",
    "class/ttuacm-backend/src/auth/auth.model.js~AuthModel.html#instance-method-updateUserByAttribute",
    "ttuacm-backend/src/auth/auth.model.js~AuthModel#updateUserByAttribute",
    "method"
  ],
  [
    "ttuacm-backend/src/auth/auth.model.js~authmodel#updateuserbyemail",
    "class/ttuacm-backend/src/auth/auth.model.js~AuthModel.html#instance-method-updateUserByEmail",
    "ttuacm-backend/src/auth/auth.model.js~AuthModel#updateUserByEmail",
    "method"
  ],
  [
    "ttuacm-backend/src/auth/auth.router.js",
    "file/ttuacm-backend/src/auth/auth.router.js.html",
    "ttuacm-backend/src/auth/auth.router.js",
    "file"
  ],
  [
    "ttuacm-backend/src/auth/auth.router.js~authrouter",
    "typedef/index.html#static-typedef-AuthRouter",
    "ttuacm-backend/src/auth/auth.router.js~AuthRouter",
    "typedef"
  ],
  [
    "ttuacm-backend/src/auth/auth.router.js~authrouter-confirmtoken",
    "typedef/index.html#static-typedef-AuthRouter-ConfirmToken",
    "ttuacm-backend/src/auth/auth.router.js~AuthRouter-ConfirmToken",
    "typedef"
  ],
  [
    "ttuacm-backend/src/auth/auth.router.js~authrouter-facebookauth",
    "typedef/index.html#static-typedef-AuthRouter-FacebookAuth",
    "ttuacm-backend/src/auth/auth.router.js~AuthRouter-FacebookAuth",
    "typedef"
  ],
  [
    "ttuacm-backend/src/auth/auth.router.js~authrouter-forgotlogin",
    "typedef/index.html#static-typedef-AuthRouter-ForgotLogin",
    "ttuacm-backend/src/auth/auth.router.js~AuthRouter-ForgotLogin",
    "typedef"
  ],
  [
    "ttuacm-backend/src/auth/auth.router.js~authrouter-githubauth",
    "typedef/index.html#static-typedef-AuthRouter-GitHubAuth",
    "ttuacm-backend/src/auth/auth.router.js~AuthRouter-GitHubAuth",
    "typedef"
  ],
  [
    "ttuacm-backend/src/auth/auth.router.js~authrouter-githubuthredirect",
    "typedef/index.html#static-typedef-AuthRouter-GitHubuthRedirect",
    "ttuacm-backend/src/auth/auth.router.js~AuthRouter-GitHubuthRedirect",
    "typedef"
  ],
  [
    "ttuacm-backend/src/auth/auth.router.js~authrouter-githubuthredirect",
    "typedef/index.html#static-typedef-AuthRouter-GitHubuthRedirect",
    "ttuacm-backend/src/auth/auth.router.js~AuthRouter-GitHubuthRedirect",
    "typedef"
  ],
  [
    "ttuacm-backend/src/auth/auth.router.js~authrouter-googleauth",
    "typedef/index.html#static-typedef-AuthRouter-GoogleAuth",
    "ttuacm-backend/src/auth/auth.router.js~AuthRouter-GoogleAuth",
    "typedef"
  ],
  [
    "ttuacm-backend/src/auth/auth.router.js~authrouter-googleauthredirect",
    "typedef/index.html#static-typedef-AuthRouter-GoogleAuthRedirect",
    "ttuacm-backend/src/auth/auth.router.js~AuthRouter-GoogleAuthRedirect",
    "typedef"
  ],
  [
    "ttuacm-backend/src/auth/auth.router.js~authrouter-login",
    "typedef/index.html#static-typedef-AuthRouter-Login",
    "ttuacm-backend/src/auth/auth.router.js~AuthRouter-Login",
    "typedef"
  ],
  [
    "ttuacm-backend/src/auth/auth.router.js~authrouter-register",
    "typedef/index.html#static-typedef-AuthRouter-Register",
    "ttuacm-backend/src/auth/auth.router.js~AuthRouter-Register",
    "typedef"
  ],
  [
    "ttuacm-backend/src/auth/auth.router.js~authrouter-resettoken",
    "typedef/index.html#static-typedef-AuthRouter-ResetToken",
    "ttuacm-backend/src/auth/auth.router.js~AuthRouter-ResetToken",
    "typedef"
  ],
  [
    "ttuacm-backend/src/auth/auth.router.js~authrouter-verifyuser",
    "typedef/index.html#static-typedef-AuthRouter-VerifyUser",
    "ttuacm-backend/src/auth/auth.router.js~AuthRouter-VerifyUser",
    "typedef"
  ],
  [
    "ttuacm-backend/src/auth/auth.router.spec.js",
    "file/ttuacm-backend/src/auth/auth.router.spec.js.html",
    "ttuacm-backend/src/auth/auth.router.spec.js",
    "file"
  ],
  [
    "ttuacm-backend/src/auth/config/oauth2.js",
    "file/ttuacm-backend/src/auth/config/oauth2.js.html",
    "ttuacm-backend/src/auth/config/oauth2.js",
    "file"
  ],
  [
    "ttuacm-backend/src/auth/config/passport.js",
    "file/ttuacm-backend/src/auth/config/passport.js.html",
    "ttuacm-backend/src/auth/config/passport.js",
    "file"
  ],
  [
    "ttuacm-backend/src/auth/index.js",
    "file/ttuacm-backend/src/auth/index.js.html",
    "ttuacm-backend/src/auth/index.js",
    "file"
  ],
  [
    "ttuacm-backend/src/contacts/contacts.app.js",
    "file/ttuacm-backend/src/contacts/contacts.app.js.html",
    "ttuacm-backend/src/contacts/contacts.app.js",
    "file"
  ],
  [
    "ttuacm-backend/src/contacts/contacts.controller.js",
    "file/ttuacm-backend/src/contacts/contacts.controller.js.html",
    "ttuacm-backend/src/contacts/contacts.controller.js",
    "file"
  ],
  [
    "ttuacm-backend/src/contacts/contacts.errors.js",
    "file/ttuacm-backend/src/contacts/contacts.errors.js.html",
    "ttuacm-backend/src/contacts/contacts.errors.js",
    "file"
  ],
  [
    "ttuacm-backend/src/contacts/contacts.model.js",
    "file/ttuacm-backend/src/contacts/contacts.model.js.html",
    "ttuacm-backend/src/contacts/contacts.model.js",
    "file"
  ],
  [
    "ttuacm-backend/src/contacts/contacts.router.js",
    "file/ttuacm-backend/src/contacts/contacts.router.js.html",
    "ttuacm-backend/src/contacts/contacts.router.js",
    "file"
  ],
  [
    "ttuacm-backend/src/contacts/contacts.router.js~contactsrouter",
    "typedef/index.html#static-typedef-ContactsRouter",
    "ttuacm-backend/src/contacts/contacts.router.js~ContactsRouter",
    "typedef"
  ],
  [
    "ttuacm-backend/src/contacts/contacts.router.js~contactsrouter",
    "typedef/index.html#static-typedef-ContactsRouter",
    "ttuacm-backend/src/contacts/contacts.router.js~ContactsRouter",
    "typedef"
  ],
  [
    "ttuacm-backend/src/contacts/index.js",
    "file/ttuacm-backend/src/contacts/index.js.html",
    "ttuacm-backend/src/contacts/index.js",
    "file"
  ],
  [
    "ttuacm-backend/src/email/email.app.js",
    "file/ttuacm-backend/src/email/email.app.js.html",
    "ttuacm-backend/src/email/email.app.js",
    "file"
  ],
  [
    "ttuacm-backend/src/email/email.controller.js",
    "file/ttuacm-backend/src/email/email.controller.js.html",
    "ttuacm-backend/src/email/email.controller.js",
    "file"
  ],
  [
    "ttuacm-backend/src/email/email.controller.js~emailcontroller#constructor",
    "class/ttuacm-backend/src/email/email.controller.js~EmailController.html#instance-constructor-constructor",
    "ttuacm-backend/src/email/email.controller.js~EmailController#constructor",
    "method"
  ],
  [
    "ttuacm-backend/src/email/email.controller.js~emailcontroller#contactus",
    "class/ttuacm-backend/src/email/email.controller.js~EmailController.html#instance-method-contactUs",
    "ttuacm-backend/src/email/email.controller.js~EmailController#contactUs",
    "method"
  ],
  [
    "ttuacm-backend/src/email/email.controller.js~emailcontroller#sendchangedpasswordemail",
    "class/ttuacm-backend/src/email/email.controller.js~EmailController.html#instance-method-sendChangedPasswordEmail",
    "ttuacm-backend/src/email/email.controller.js~EmailController#sendChangedPasswordEmail",
    "method"
  ],
  [
    "ttuacm-backend/src/email/email.controller.js~emailcontroller#sendconfirmationemail",
    "class/ttuacm-backend/src/email/email.controller.js~EmailController.html#instance-method-sendConfirmationEmail",
    "ttuacm-backend/src/email/email.controller.js~EmailController#sendConfirmationEmail",
    "method"
  ],
  [
    "ttuacm-backend/src/email/email.controller.js~emailcontroller#sendresetemail",
    "class/ttuacm-backend/src/email/email.controller.js~EmailController.html#instance-method-sendResetEmail",
    "ttuacm-backend/src/email/email.controller.js~EmailController#sendResetEmail",
    "method"
  ],
  [
    "ttuacm-backend/src/email/email.router.js",
    "file/ttuacm-backend/src/email/email.router.js.html",
    "ttuacm-backend/src/email/email.router.js",
    "file"
  ],
  [
    "ttuacm-backend/src/email/email.router.js~emailrouter",
    "typedef/index.html#static-typedef-EmailRouter",
    "ttuacm-backend/src/email/email.router.js~EmailRouter",
    "typedef"
  ],
  [
    "ttuacm-backend/src/email/email.router.js~emailrouter-contactus",
    "typedef/index.html#static-typedef-EmailRouter-contactUs",
    "ttuacm-backend/src/email/email.router.js~EmailRouter-contactUs",
    "typedef"
  ],
  [
    "ttuacm-backend/src/email/email.router.js~emailrouter-sendchangedpasswordnotification",
    "typedef/index.html#static-typedef-EmailRouter-sendChangedPasswordNotification",
    "ttuacm-backend/src/email/email.router.js~EmailRouter-sendChangedPasswordNotification",
    "typedef"
  ],
  [
    "ttuacm-backend/src/email/email.router.js~emailrouter-sendconfirmationemail",
    "typedef/index.html#static-typedef-EmailRouter-sendConfirmationEmail",
    "ttuacm-backend/src/email/email.router.js~EmailRouter-sendConfirmationEmail",
    "typedef"
  ],
  [
    "ttuacm-backend/src/email/email.router.js~emailrouter-sendresetemail",
    "typedef/index.html#static-typedef-EmailRouter-sendResetEmail",
    "ttuacm-backend/src/email/email.router.js~EmailRouter-sendResetEmail",
    "typedef"
  ],
  [
    "ttuacm-backend/src/email/index.js",
    "file/ttuacm-backend/src/email/index.js.html",
    "ttuacm-backend/src/email/index.js",
    "file"
  ],
  [
    "ttuacm-backend/src/events/events.app.js",
    "file/ttuacm-backend/src/events/events.app.js.html",
    "ttuacm-backend/src/events/events.app.js",
    "file"
  ],
  [
    "ttuacm-backend/src/events/events.controller.js",
    "file/ttuacm-backend/src/events/events.controller.js.html",
    "ttuacm-backend/src/events/events.controller.js",
    "file"
  ],
  [
    "ttuacm-backend/src/events/events.controller.js~eventscontroller#addattendee",
    "class/ttuacm-backend/src/events/events.controller.js~EventsController.html#instance-method-addAttendee",
    "ttuacm-backend/src/events/events.controller.js~EventsController#addAttendee",
    "method"
  ],
  [
    "ttuacm-backend/src/events/events.controller.js~eventscontroller#calendar",
    "class/ttuacm-backend/src/events/events.controller.js~EventsController.html#instance-member-calendar",
    "ttuacm-backend/src/events/events.controller.js~EventsController#calendar",
    "member"
  ],
  [
    "ttuacm-backend/src/events/events.controller.js~eventscontroller#calendarid",
    "class/ttuacm-backend/src/events/events.controller.js~EventsController.html#instance-member-calendarId",
    "ttuacm-backend/src/events/events.controller.js~EventsController#calendarId",
    "member"
  ],
  [
    "ttuacm-backend/src/events/events.controller.js~eventscontroller#constructor",
    "class/ttuacm-backend/src/events/events.controller.js~EventsController.html#instance-constructor-constructor",
    "ttuacm-backend/src/events/events.controller.js~EventsController#constructor",
    "method"
  ],
  [
    "ttuacm-backend/src/events/events.controller.js~eventscontroller#currentattendees",
    "class/ttuacm-backend/src/events/events.controller.js~EventsController.html#instance-member-currentAttendees",
    "ttuacm-backend/src/events/events.controller.js~EventsController#currentAttendees",
    "member"
  ],
  [
    "ttuacm-backend/src/events/events.controller.js~eventscontroller#getattendees",
    "class/ttuacm-backend/src/events/events.controller.js~EventsController.html#instance-method-getAttendees",
    "ttuacm-backend/src/events/events.controller.js~EventsController#getAttendees",
    "method"
  ],
  [
    "ttuacm-backend/src/events/events.controller.js~eventscontroller#getrawevents",
    "class/ttuacm-backend/src/events/events.controller.js~EventsController.html#instance-method-getRawEvents",
    "ttuacm-backend/src/events/events.controller.js~EventsController#getRawEvents",
    "method"
  ],
  [
    "ttuacm-backend/src/events/events.controller.js~eventscontroller#listevents",
    "class/ttuacm-backend/src/events/events.controller.js~EventsController.html#instance-method-listEvents",
    "ttuacm-backend/src/events/events.controller.js~EventsController#listEvents",
    "method"
  ],
  [
    "ttuacm-backend/src/events/events.controller.js~eventscontroller#removeattendee",
    "class/ttuacm-backend/src/events/events.controller.js~EventsController.html#instance-method-removeAttendee",
    "ttuacm-backend/src/events/events.controller.js~EventsController#removeAttendee",
    "method"
  ],
  [
    "ttuacm-backend/src/events/events.controller.js~eventscontroller#updateattendee",
    "class/ttuacm-backend/src/events/events.controller.js~EventsController.html#instance-method-updateAttendee",
    "ttuacm-backend/src/events/events.controller.js~EventsController#updateAttendee",
    "method"
  ],
  [
    "ttuacm-backend/src/events/events.router.js",
    "file/ttuacm-backend/src/events/events.router.js.html",
    "ttuacm-backend/src/events/events.router.js",
    "file"
  ],
  [
    "ttuacm-backend/src/events/events.router.js~eventsrouter",
    "typedef/index.html#static-typedef-EventsRouter",
    "ttuacm-backend/src/events/events.router.js~EventsRouter",
    "typedef"
  ],
  [
    "ttuacm-backend/src/events/events.router.js~eventsrouter-addattendee",
    "typedef/index.html#static-typedef-EventsRouter-addAttendee",
    "ttuacm-backend/src/events/events.router.js~EventsRouter-addAttendee",
    "typedef"
  ],
  [
    "ttuacm-backend/src/events/events.router.js~eventsrouter-getattendees",
    "typedef/index.html#static-typedef-EventsRouter-getAttendees",
    "ttuacm-backend/src/events/events.router.js~EventsRouter-getAttendees",
    "typedef"
  ],
  [
    "ttuacm-backend/src/events/events.router.js~eventsrouter-getrawevents",
    "typedef/index.html#static-typedef-EventsRouter-getRawEvents",
    "ttuacm-backend/src/events/events.router.js~EventsRouter-getRawEvents",
    "typedef"
  ],
  [
    "ttuacm-backend/src/events/events.router.js~eventsrouter-listevents",
    "typedef/index.html#static-typedef-EventsRouter-listEvents",
    "ttuacm-backend/src/events/events.router.js~EventsRouter-listEvents",
    "typedef"
  ],
  [
    "ttuacm-backend/src/events/events.router.js~eventsrouter-removeattendee",
    "typedef/index.html#static-typedef-EventsRouter-removeAttendee",
    "ttuacm-backend/src/events/events.router.js~EventsRouter-removeAttendee",
    "typedef"
  ],
  [
    "ttuacm-backend/src/events/index.js",
    "file/ttuacm-backend/src/events/index.js.html",
    "ttuacm-backend/src/events/index.js",
    "file"
  ],
  [
    "ttuacm-backend/src/profile/index.js",
    "file/ttuacm-backend/src/profile/index.js.html",
    "ttuacm-backend/src/profile/index.js",
    "file"
  ],
  [
    "ttuacm-backend/src/profile/profile.app.js",
    "file/ttuacm-backend/src/profile/profile.app.js.html",
    "ttuacm-backend/src/profile/profile.app.js",
    "file"
  ],
  [
    "ttuacm-backend/src/profile/profile.controller.js",
    "file/ttuacm-backend/src/profile/profile.controller.js.html",
    "ttuacm-backend/src/profile/profile.controller.js",
    "file"
  ],
  [
    "ttuacm-backend/src/profile/profile.model.js",
    "file/ttuacm-backend/src/profile/profile.model.js.html",
    "ttuacm-backend/src/profile/profile.model.js",
    "file"
  ],
  [
    "ttuacm-backend/src/profile/profile.router.js",
    "file/ttuacm-backend/src/profile/profile.router.js.html",
    "ttuacm-backend/src/profile/profile.router.js",
    "file"
  ],
  [
    "ttuacm-backend/src/profile/profile.router.js~userrouter-getprofile",
    "typedef/index.html#static-typedef-UserRouter-getProfile",
    "ttuacm-backend/src/profile/profile.router.js~UserRouter-getProfile",
    "typedef"
  ],
  [
    "ttuacm-backend/src/profile/profile.router.js~userrouter-updateresume",
    "typedef/index.html#static-typedef-UserRouter-updateResume",
    "ttuacm-backend/src/profile/profile.router.js~UserRouter-updateResume",
    "typedef"
  ],
  [
    "ttuacm-backend/src/profile/profile.router.js~userrouter-updateuser",
    "typedef/index.html#static-typedef-UserRouter-updateUser",
    "ttuacm-backend/src/profile/profile.router.js~UserRouter-updateUser",
    "typedef"
  ],
  [
    "ttuacm-backend/src/utils/db-connect.js",
    "file/ttuacm-backend/src/utils/db-connect.js.html",
    "ttuacm-backend/src/utils/db-connect.js",
    "file"
  ],
  [
    "ttuacm-backend/src/utils/generate-hex.js",
    "file/ttuacm-backend/src/utils/generate-hex.js.html",
    "ttuacm-backend/src/utils/generate-hex.js",
    "file"
  ],
  [
    "ttuacm-backend/src/utils/generate-jwt.js",
    "file/ttuacm-backend/src/utils/generate-jwt.js.html",
    "ttuacm-backend/src/utils/generate-jwt.js",
    "file"
  ],
  [
    "ttuacm-backend/src/utils/protected-route.js",
    "file/ttuacm-backend/src/utils/protected-route.js.html",
    "ttuacm-backend/src/utils/protected-route.js",
    "file"
  ],
  [
    "ttuacm-backend/src/utils/request.js",
    "file/ttuacm-backend/src/utils/request.js.html",
    "ttuacm-backend/src/utils/request.js",
    "file"
  ],
  [
    "ttuacm-backend/src/utils/request.js~request#body",
    "class/ttuacm-backend/src/utils/request.js~Request.html#instance-method-body",
    "ttuacm-backend/src/utils/request.js~Request#body",
    "method"
  ],
  [
    "ttuacm-backend/src/utils/request.js~request#constructor",
    "class/ttuacm-backend/src/utils/request.js~Request.html#instance-constructor-constructor",
    "ttuacm-backend/src/utils/request.js~Request#constructor",
    "method"
  ],
  [
    "ttuacm-backend/src/utils/request.js~request#end",
    "class/ttuacm-backend/src/utils/request.js~Request.html#instance-method-end",
    "ttuacm-backend/src/utils/request.js~Request#end",
    "method"
  ],
  [
    "ttuacm-backend/src/utils/request.js~request#params",
    "class/ttuacm-backend/src/utils/request.js~Request.html#instance-method-params",
    "ttuacm-backend/src/utils/request.js~Request#params",
    "method"
  ],
  [
    "ttuacm-backend/src/utils/request.js~request#path",
    "class/ttuacm-backend/src/utils/request.js~Request.html#instance-method-path",
    "ttuacm-backend/src/utils/request.js~Request#path",
    "method"
  ]
]